---
- hosts: localhost

  tasks:
    - name: Create EC2 key
      ec2_key:
        # TODO: Pass in aws --profile from makefile or ENV VAR
        # profile: "mc_server"
        name: "minecraft_key"
        # Region is not required since its defined in profile in ~/.aws/config
        # region: "us-west-1"
      register: ec2_key

    - name: save private key
      copy:
        content: "{{ ec2_key.key.private_key }}" 
        dest: "./minecraft_key.pem" 
        mode: '0600'
      when: ec2_key.changed

